Class {
	#name : 'VESTest',
	#superclass : 'TestCase',
	#category : 'VisualizationEvoSuite',
	#package : 'VisualizationEvoSuite'
}

{ #category : 'example' }
VESTest >> codeExample [
^' Initial population: { 
-813251331: { fitness: 328.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
Integer integer0 = stack0.pop();
int int0 = (-190);
Integer integer1 = new Integer(int0);
stack0.push(integer1);
int int1 = 0;
Integer integer2 = new Integer(int1);
stack0.push(integer2);
stack0.pop();
stack0.push(integer0);
Integer integer3 = stack0.pop();
stack0.pop();
stack0.push(integer3);
stack0.pop();
int int2 = 1179;
Integer integer4 = new Integer(int2);
stack0.push(integer4);
Integer integer5 = null;
stack0.pop();
stack0.push(integer5);
stack0.pop();
stack0.isEmpty();
stack0.pop();
stack0.push(integer5);
Integer integer6 = new Integer(int0);
stack0.push(integer6);
stack0.isEmpty();
int int3 = (-720);
Integer integer7 = new Integer(int3);
stack0.push(integer7);
stack0.push(integer6);
stack0.isEmpty();
stack0.pop();

	}
},
318957721: { fitness: 328.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 0;
Integer integer0 = new Integer(int0);
stack0.pop();
stack0.pop();
stack0.pop();
stack0.push(integer0);
int int1 = 510;
Integer integer1 = new Integer(int1);
stack0.push(integer1);
stack0.pop();
stack0.pop();
stack0.pop();
stack0.pop();
stack0.pop();
stack0.pop();
stack0.pop();
stack0.isEmpty();
stack0.isEmpty();
stack0.isEmpty();
stack0.isEmpty();
stack0.pop();
stack0.isEmpty();
stack0.isEmpty();
stack0.pop();
stack0.isEmpty();

	}
},
-283280998: { fitness: 328.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
Integer integer0 = stack0.pop();
int int0 = 10;
Integer integer1 = new Integer(int0);
int int1 = 1197;
Integer integer2 = new Integer(int1);
stack0.push(integer2);
stack0.push(integer1);
int int2 = 0;
Integer integer3 = stack0.pop();
stack0.pop();
stack0.push(integer0);
Integer integer4 = new Integer(int2);
stack0.push(integer4);
Integer integer5 = stack0.pop();
stack0.pop();
int int3 = 0;
Integer integer6 = new Integer(int3);
stack0.push(integer6);
Integer integer7 = new Integer(int3);
stack0.push(integer7);
stack0.isEmpty();
stack0.push(integer5);
stack0.isEmpty();
stack0.push(integer3);
stack0.push(integer3);
stack0.pop();
Integer integer8 = new Integer(int0);
stack0.push(integer8);
Integer integer9 = new Integer(int1);
stack0.push(integer9);
stack0.isEmpty();
stack0.pop();
Integer integer10 = new Integer(int3);
stack0.push(integer10);

	}
},
-1573742581: { fitness: 328.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 1;
Integer integer0 = stack0.pop();
Integer integer1 = new Integer(int0);
Integer integer2 = stack0.pop();
stack0.push(integer1);
int int1 = 905;
Integer integer3 = new Integer(int1);
stack0.push(integer3);
Integer integer4 = stack0.pop();
stack0.push(integer1);
stack0.push(integer4);
stack0.isEmpty();
stack0.pop();
stack0.isEmpty();
stack0.push(integer0);
Integer integer5 = stack0.pop();
stack0.pop();
Integer integer6 = null;
stack0.push(integer6);
int int2 = 1;
Integer integer7 = new Integer(int2);
stack0.push(integer7);
stack0.isEmpty();
stack0.isEmpty();
stack0.push(integer2);
stack0.pop();
stack0.isEmpty();
stack0.pop();
stack0.isEmpty();
stack0.pop();
stack0.isEmpty();
stack0.push(integer5);

	}
},
-425546632: { fitness: 328.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
stack0.pop();
stack0.isEmpty();
stack0.pop();
int int0 = (-1);
Integer integer0 = new Integer(int0);
stack0.push(integer0);
stack0.isEmpty();
stack0.isEmpty();
Integer integer1 = stack0.pop();
stack0.pop();
stack0.push(integer1);
stack0.isEmpty();
stack0.push(integer0);

	}
},
-1312026187: { fitness: 328.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 0;
stack0.pop();
Integer integer0 = new Integer(int0);
stack0.push(integer0);
stack0.isEmpty();
stack0.pop();
stack0.pop();
int int1 = 1;
Integer integer1 = new Integer(int1);
stack0.push(integer1);

	}
},
53203191: { fitness: 8.647619, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 581;
Integer integer0 = new Integer(int0);
stack0.push(integer0);
stack0.push(integer0);
int int1 = 1;
stack0.push(integer0);
Integer integer1 = new Integer(int1);
int int2 = 657;
Integer integer2 = new Integer(int2);
stack0.push(integer2);
stack0.push(integer2);
stack0.push(integer1);
stack0.isEmpty();
Integer integer3 = stack0.pop();
Integer integer4 = stack0.pop();
Integer integer5 = stack0.pop();
Integer integer6 = stack0.pop();
Integer integer7 = stack0.pop();
stack0.push(integer3);
stack0.pop();
stack0.push(integer3);
stack0.push(integer5);
stack0.isEmpty();
stack0.push(integer7);
stack0.push(integer4);
stack0.push(integer6);
stack0.pop();
stack0.push(integer1);
stack0.isEmpty();

	}
},
782087956: { fitness: 94.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
Integer integer0 = stack0.pop();
stack0.pop();
stack0.push(integer0);
stack0.isEmpty();
stack0.isEmpty();
stack0.isEmpty();
stack0.isEmpty();
int int0 = 4672;
Integer integer1 = new Integer(int0);
stack0.push(integer1);

	}
},
-743611664: { fitness: 94.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
Integer integer0 = stack0.pop();
int int0 = 0;
Integer integer1 = new Integer(int0);
stack0.pop();
stack0.push(integer0);
stack0.push(integer1);
int int1 = (-2570);
stack0.pop();
Integer integer2 = new Integer(int1);
stack0.push(integer2);
Integer integer3 = stack0.pop();
int int2 = 0;
Integer integer4 = new Integer(int2);
stack0.push(integer4);
stack0.isEmpty();
stack0.push(integer3);
stack0.pop();
stack0.push(integer3);
stack0.push(integer2);
stack0.push(integer3);
stack0.pop();
stack0.pop();
stack0.isEmpty();
stack0.isEmpty();
stack0.isEmpty();

	}
},
-910249576: { fitness: 94.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
stack0.isEmpty();
int int0 = 1;
Integer integer0 = new Integer(int0);
stack0.push(integer0);
Integer integer1 = new Integer(int0);
stack0.push(integer1);

	}
},
937756683: { fitness: 94.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
Integer integer0 = stack0.pop();
stack0.pop();
stack0.pop();
Integer integer1 = stack0.pop();
stack0.pop();
stack0.push(integer1);
int int0 = 628;
stack0.pop();
Integer integer2 = new Integer(int0);
stack0.push(integer2);
stack0.isEmpty();
stack0.push(integer0);
int int1 = 0;
Integer integer3 = new Integer(int1);
stack0.push(integer3);
stack0.pop();
stack0.isEmpty();
stack0.isEmpty();
Integer integer4 = new Integer(int0);
stack0.push(integer4);
stack0.pop();
stack0.isEmpty();

	}
},
617335633: { fitness: 94.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
Integer integer0 = stack0.pop();
int int0 = 0;
Integer integer1 = new Integer(int0);
stack0.push(integer1);
Integer integer2 = new Integer(int0);
stack0.push(integer2);
stack0.pop();
int int1 = 1;
stack0.pop();
Integer integer3 = new Integer(int1);
stack0.push(integer3);
stack0.isEmpty();
int int2 = 583;
Integer integer4 = new Integer(int2);
stack0.push(integer4);
stack0.push(integer0);
stack0.pop();
Integer integer5 = stack0.pop();
stack0.pop();
stack0.isEmpty();
stack0.pop();
stack0.push(integer5);
int int3 = (-353);
stack0.pop();
int int4 = 2006;
Integer integer6 = new Integer(int4);
stack0.push(integer6);
Integer integer7 = new Integer(int3);
stack0.pop();
stack0.push(integer7);
stack0.isEmpty();
stack0.pop();
stack0.pop();
stack0.isEmpty();
stack0.push(integer5);
stack0.isEmpty();
int int5 = 10;
Integer integer8 = new Integer(int5);
stack0.push(integer8);

	}
},
490388559: { fitness: 94.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
Integer integer0 = stack0.pop();
stack0.pop();
int int0 = 0;
Integer integer1 = new Integer(int0);
stack0.push(integer1);
stack0.pop();
stack0.pop();
stack0.pop();
int int1 = 3227;
Integer integer2 = new Integer(int1);
stack0.push(integer2);
int int2 = 0;
stack0.pop();
Integer integer3 = new Integer(int2);
stack0.push(integer3);
stack0.push(integer0);
stack0.pop();
int int3 = 0;
Integer integer4 = new Integer(int3);
stack0.push(integer4);

	}
},
698176219: { fitness: 7.218182, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 10;
Integer integer0 = new Integer(int0);
Integer integer1 = new Integer(int0);
stack0.push(integer1);
stack0.push(integer0);
stack0.pop();
Integer integer2 = null;
stack0.pop();
stack0.push(integer2);
stack0.isEmpty();
stack0.isEmpty();
stack0.isEmpty();
stack0.push(integer2);
Integer integer3 = null;
stack0.pop();
stack0.push(integer3);
stack0.pop();
stack0.isEmpty();
stack0.isEmpty();

	}
},
1949551727: { fitness: 93.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
Integer integer0 = stack0.pop();
stack0.isEmpty();
int int0 = 4749;
Integer integer1 = new Integer(int0);
stack0.push(integer1);
stack0.push(integer0);
stack0.push(integer1);
Integer integer2 = stack0.pop();
int int1 = 1;
Integer integer3 = new Integer(int1);
Integer integer4 = stack0.pop();
stack0.push(integer3);
stack0.isEmpty();
stack0.push(integer2);
stack0.isEmpty();
stack0.pop();
stack0.push(integer2);
stack0.push(integer4);

	}
},
-1063605212: { fitness: 7.188889, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = (-1);
Integer integer0 = new Integer(int0);
stack0.push(integer0);
int int1 = 0;
Integer integer1 = stack0.pop();
Integer integer2 = new Integer(int1);
stack0.push(integer2);
stack0.isEmpty();
int int2 = (-1694);
Integer integer3 = null;
stack0.push(integer3);
Integer integer4 = new Integer(int2);
stack0.push(integer4);
stack0.pop();
stack0.pop();
stack0.isEmpty();
stack0.isEmpty();
stack0.push(integer0);
stack0.push(integer1);

	}
},
1644572515: { fitness: 43.468182, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 0;
Integer integer0 = new Integer(int0);
stack0.push(integer0);
int int1 = 0;
Integer integer1 = new Integer(int1);
stack0.push(integer1);
stack0.pop();

	}
},
-1535993803: { fitness: 93.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 0;
Integer integer0 = new Integer(int0);
int int1 = 0;
stack0.pop();
Integer integer1 = new Integer(int1);
stack0.push(integer1);
int int2 = 0;
Integer integer2 = new Integer(int2);
stack0.push(integer2);
Integer integer3 = stack0.pop();
Integer integer4 = new Integer(int0);
stack0.push(integer4);
stack0.push(integer0);
stack0.isEmpty();
int int3 = 0;
Integer integer5 = new Integer(int3);
stack0.push(integer5);
stack0.push(integer5);
stack0.push(integer3);

	}
},
1821286613: { fitness: 93.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
Integer integer0 = stack0.pop();
stack0.isEmpty();
Integer integer1 = null;
stack0.pop();
stack0.push(integer1);
stack0.push(integer0);
stack0.pop();
stack0.push(integer0);
int int0 = 0;
Integer integer2 = new Integer(int0);
stack0.pop();
stack0.pop();
stack0.push(integer2);
stack0.isEmpty();
stack0.pop();
int int1 = (-1);
Integer integer3 = new Integer(int1);
stack0.push(integer3);
int int2 = (-1);
Integer integer4 = new Integer(int2);
stack0.push(integer4);
Integer integer5 = new Integer(int2);
stack0.push(integer5);

	}
},
159424994: { fitness: 43.409091, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 2808;
Integer integer0 = new Integer(int0);
stack0.push(integer0);
stack0.pop();

	}
},
1904921837: { fitness: 43.188889, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = (-2640);
int int1 = 0;
Integer integer0 = new Integer(int1);
stack0.push(integer0);
Integer integer1 = new Integer(int0);
stack0.push(integer1);
Integer integer2 = new Integer(int0);
stack0.push(integer2);
stack0.pop();
stack0.pop();
stack0.pop();
stack0.pop();

	}
},
1807857197: { fitness: 93.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
Integer integer0 = stack0.pop();
int int0 = 1733;
int int1 = 1495;
Integer integer1 = new Integer(int1);
stack0.push(integer1);
Integer integer2 = new Integer(int0);
int int2 = 10;
stack0.push(integer1);
Integer integer3 = new Integer(int2);
stack0.push(integer3);
Integer integer4 = stack0.pop();
Integer integer5 = stack0.pop();
stack0.push(integer5);
stack0.push(integer2);
Integer integer6 = stack0.pop();
stack0.pop();
stack0.push(integer5);
int int3 = (-196);
stack0.pop();
Integer integer7 = new Integer(int3);
stack0.push(integer7);
stack0.isEmpty();
stack0.isEmpty();
stack0.push(integer0);
stack0.push(integer4);
stack0.push(integer5);
stack0.push(integer2);
stack0.pop();
stack0.pop();
stack0.push(integer6);
stack0.push(integer7);
stack0.isEmpty();
stack0.pop();
stack0.isEmpty();

	}
},
853734581: { fitness: 93.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
int int0 = (-269);
Integer integer0 = new Integer(int0);
stack0.push(integer0);
stack0.pop();
Integer integer1 = new Integer(int0);
stack0.push(integer1);
stack0.pop();
stack0.pop();
stack0.pop();
Integer integer2 = new Integer(int0);
stack0.push(integer2);
stack0.isEmpty();
stack0.push(integer0);
Integer integer3 = new Integer(int0);
stack0.push(integer3);
Integer integer4 = new Integer(int0);
stack0.push(integer4);
stack0.isEmpty();
stack0.isEmpty();
stack0.push(integer1);
Integer integer5 = new Integer(int0);
stack0.push(integer5);
stack0.push(integer4);
stack0.pop();
stack0.pop();
stack0.pop();
stack0.push(integer0);

	}
},
754288895: { fitness: 93.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
Integer integer0 = stack0.pop();
Integer integer1 = stack0.pop();
Integer integer2 = stack0.pop();
stack0.push(integer1);
stack0.pop();
int int0 = (-745);
stack0.push(integer0);
Integer integer3 = new Integer(int0);
stack0.push(integer2);
stack0.push(integer3);
int int1 = 1;
Integer integer4 = null;
stack0.push(integer4);
Integer integer5 = new Integer(int1);
stack0.push(integer4);
Integer integer6 = stack0.pop();
stack0.push(integer5);
stack0.push(integer1);
stack0.push(integer6);
Integer integer7 = stack0.pop();
Integer integer8 = new Integer(int1);
stack0.push(integer8);
stack0.push(integer5);
stack0.push(integer7);
Integer integer9 = stack0.pop();
stack0.pop();
stack0.pop();
stack0.isEmpty();
stack0.push(integer9);
Integer integer10 = stack0.pop();
stack0.isEmpty();
stack0.push(integer10);
stack0.push(integer6);
stack0.isEmpty();

	}
},
-1429658766: { fitness: 93.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
int int0 = 2268;
int int1 = 0;
stack0.pop();
Integer integer0 = new Integer(int1);
stack0.push(integer0);
Integer integer1 = new Integer(int0);
stack0.push(integer1);
stack0.push(integer1);
stack0.push(integer1);
stack0.pop();
Integer integer2 = stack0.pop();
stack0.pop();
Integer integer3 = stack0.pop();
Integer integer4 = stack0.pop();
stack0.pop();
stack0.pop();
stack0.isEmpty();
Integer integer5 = new Integer(int1);
stack0.push(integer5);
stack0.push(integer3);
stack0.push(integer2);
stack0.pop();
stack0.isEmpty();
stack0.isEmpty();
stack0.push(integer3);
stack0.push(integer4);
stack0.push(integer1);
Integer integer6 = new Integer(int0);
stack0.push(integer6);
stack0.pop();
stack0.pop();
int int2 = 0;
Integer integer7 = new Integer(int2);
stack0.push(integer7);
stack0.pop();
stack0.pop();
stack0.pop();

	}
},'
]

{ #category : 'example' }
VESTest >> codeIndividualExample [
^ '-813251331: { fitness: 328.500000, code:{
Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
Integer integer0 = stack0.pop();
int int0 = (-190);
Integer integer1 = new Integer(int0);
stack0.push(integer1);
int int1 = 0;
Integer integer2 = new Integer(int1);
stack0.push(integer2);
stack0.pop();
stack0.push(integer0);
Integer integer3 = stack0.pop();
stack0.pop();
stack0.push(integer3);
stack0.pop();
int int2 = 1179;
Integer integer4 = new Integer(int2);
stack0.push(integer4);
Integer integer5 = null;
stack0.pop();
stack0.push(integer5);
stack0.pop();
stack0.isEmpty();
stack0.pop();
stack0.push(integer5);
Integer integer6 = new Integer(int0);
stack0.push(integer6);
stack0.isEmpty();
int int3 = (-720);
Integer integer7 = new Integer(int3);
stack0.push(integer7);
stack0.push(integer6);
stack0.isEmpty();
stack0.pop();

	}
},'
]

{ #category : 'tests' }
VESTest >> testEmpty [
	self assert: VESGeneration new numberOfIndividuals equals: 0.
	self assert: VESModel new numberOfIndividuals equals: 0.
	self assert: VESModel new numberOfGenerations equals: 0.
]

{ #category : 'tests' }
VESTest >> testExample [
	| model |
	model := VESModel new.
	model importFromString: self codeExample.
	
]

{ #category : 'tests' }
VESTest >> testIndividual [
	| model ind |
	model := VESModel new.
	ind := model importIndividualFromString: self codeIndividualExample.
	
	self assert: ind esHash equals: '-813251331'.
	self assert: ind fitness equals: 328.500000.
	self assert: ind code equals: 
'Stack<Integer> stack0 = new Stack<Integer>();
stack0.pop();
Integer integer0 = stack0.pop();
int int0 = (-190);
Integer integer1 = new Integer(int0);
stack0.push(integer1);
int int1 = 0;
Integer integer2 = new Integer(int1);
stack0.push(integer2);
stack0.pop();
stack0.push(integer0);
Integer integer3 = stack0.pop();
stack0.pop();
stack0.push(integer3);
stack0.pop();
int int2 = 1179;
Integer integer4 = new Integer(int2);
stack0.push(integer4);
Integer integer5 = null;
stack0.pop();
stack0.push(integer5);
stack0.pop();
stack0.isEmpty();
stack0.pop();
stack0.push(integer5);
Integer integer6 = new Integer(int0);
stack0.push(integer6);
stack0.isEmpty();
int int3 = (-720);
Integer integer7 = new Integer(int3);
stack0.push(integer7);
stack0.push(integer6);
stack0.isEmpty();
stack0.pop();'
]
